services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
      - cache:/var/www/html/bootstrap/cache
    depends_on:
      - mysql
      - redis
    command: php-fpm

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "56379:6379"

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
      - cache:/var/www/html/bootstrap/cache
    command: sh -lc "php artisan queue:work --tries=2 --backoff=3 --timeout=120"
    depends_on:
      - app
      - redis
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -lc "php artisan schedule:work"
    depends_on:
      - app
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"

volumes:
  mysql_data:
  vendor:
  cache:
