zend_extension=xdebug
xdebug.mode=debug,develop
xdebug.start_with_request=yes

; где слушатель (VS Code) — это ХОСТ
xdebug.client_host=host.docker.internal
xdebug.client_port=9003

; на Linux Docker Desktop добавь extra_hosts (ниже)
xdebug.discover_client_host=0

; опционально лог Xdebug
xdebug.log=/tmp/xdebug.log
xdebug.log_level=7
